#!/bin/bash

echo -e "\n\n===== Check Inventory Server  ==================== 

If nothing shows below, the scanners are not running.

";

launchctl list | grep scan | grep -v XP

echo -e "

(use startAllScanners to start them)
==========================================

";

