#!/bin/bash

echo -e "\n\n===== Check Inventory Server  ==================== ";

If nothing shows below, the scanners are not running.

launchctl list | grep scan

echo -e "\n\n========================================== \n";

