#!/bin/bash

if [[ -z "$1" ]]; then
echo -e "\n\nERROR: You must supply a commit message";
exit;
fi


pushd $scanProjectBase/system > /dev/null
echo -e "\n\nINVENTORY SCANNER SERVER";
git status;
echo -e "\n\nADDING & COMMITTING =======\n\n";

git add --all .

git commit -m"$1"

echo -e "\n\nPUSHING =======\n\n";
git push
echo -e "\n\nFINISHED ======= Inventory Scanner Server\n\n";

popd > /dev/null

pushd $scanProjectBase/system/node_modules/helixConnector > /dev/null
echo -e "\n\nHELIX CONNECTOR";
git status;
echo -e "\n\nADDING & COMMITTING =======\n\n";

git add --all .

git commit -m"$1"

echo -e "\n\nPUSHING =======\n\n";
git push
echo -e "\n\nFINISHED ======= Helix Connector\n\n";

popd > /dev/null

pushd $scanProjectBase/node_modules > /dev/null
echo -e "\n\nQTOOLS UTILITIES";
git status;
echo -e "\n\nADDING & COMMITTING =======\n\n";

git add --all .

git commit -m"$1"

echo -e "\n\nPUSHING =======\n\n";
git push
echo -e "\n\nFINISHED ======= qTools Utilities\n\n";

popd > /dev/null