#!/bin/bash

if [[ -z "$1" ]]; then
echo -e "\n\nERROR: You must supply a commit message";
exit;
fi


pushd $scanProjectBase/system > /dev/null
echo -e "\n\nINVENTORY SCANNER SERVER\n";
pwd;
echo -e "\n";
git status;
echo -e "\nADDING & COMMITTING =======\n\n";

git add --all .

git commit -m"$1"

echo -e "\nPUSHING =======\n\n";
git push
echo -e "\nFINISHED ======= Inventory Scanner Server\n\n";

popd > /dev/null


pushd $scanProjectBase/system/node_modules/helixConnector > /dev/null
echo -e "\n\nHELIX CONNECTOR\n";
pwd;
echo -e "\n";
git status;
echo -e "\nADDING & COMMITTING =======\n\n";

git add --all .

git commit -m"$1"

echo -e "\nPUSHING =======\n\n";
git push
echo -e "\nFINISHED ======= Helix Connector\n\n";

popd > /dev/null


pushd $scanProjectBase/node_modules > /dev/null
echo -e "\n\nQTOOLS UTILITIES\n";
pwd;
echo -e "\n";
git status;
echo -e "\nADDING & COMMITTING =======\n\n";

git add --all .

git commit -m"$1"

echo -e "\nPUSHING =======\n\n";
git push
echo -e "\nFINISHED ======= qTools Utilities\n\n";

popd > /dev/null