#!/bin/bash
echo $scanProjectBase;
echo "--------";

echo -e "\n\n===== Stopping Inventor Scanner Servers ==================== \n";
echo -e "(no message == successful stop; error message means it probably wasn't running anyway)\n"

forever stopall --silent  > /dev/null

echo -e "\n\n===== Starting Inventor Scanner Servers ==================== \n";

export SCANNER_PORT=1337

echo -e "\n\nStarting scanner $SCANNER_PORT\n\n" >> {scanProjectBase}/system/management/logs/foreverServer.log;

forever start \
--watch \
--watchDirectory ${scanProjectBase}/system \
--spinSleepTime 10000 \
--append \
-l ${scanProjectBase}/system/management/logs/foreverServer.log \
${scanProjectBase}/system/scanServer/scanServer.js 

echo -e "Scanner started for port $SCANNER_PORT";

export SCANNER_PORT=1338

echo -e "\n\nStarting scanner $SCANNER_PORT\n\n" >> {scanProjectBase}/system/management/logs/foreverServer.log;

forever start \
--watch \
--watchDirectory ${scanProjectBase}/system \
--spinSleepTime 10000 \
--append \
-l ${scanProjectBase}/system/management/logs/foreverServer.log \
${scanProjectBase}/system/scanServer/scanServer.js 

echo -e "Scanner started for port $SCANNER_PORT";

echo -e "\n\n========================================== \n";

tail -f ${scanProjectBase}/system/management/logs/foreverServer.log

