#!/bin/bash


pushd /Users/HelixServer/Library/LaunchAgents > /dev/null

for plist in com.databright.tqwhite.scannerServer.*.plist; do
  echo "Bootstrapping $plist"
  launchctl bootstrap gui/$(id -u) "$PWD/$plist" || echo "❌ Failed: $plist"
done

popd > /dev/null