#!/bin/bash

echo -e "\n\n===== Stopping Inventory Server  ==================== ";
echo -e "(no message == successful stop; error message means it probably wasn't running anyway)\n"

forever stopall --silent  > /dev/null

echo -e "\n\n========================================== \n";

