#!/bin/bash


pushd /Users/HelixServer/Library/LaunchAgents > /dev/null

for plist in com.databright.tqwhite.scannerServer.*.plist; do
  echo "Bootout $plist"
  launchctl bootout gui/$(id -u) "$PWD/$plist" || echo "❌ Not loaded: $plist"
done

popd > /dev/null