#!/bin/bash
launchctl unload /Users/HelixServer/Library/LaunchAgents/scanServer1337.plist
launchctl unload /Users/HelixServer/Library/LaunchAgents/scanServer1338.plist
launchctl unload /Users/HelixServer/Library/LaunchAgents/scanServer1339.plist
launchctl unload /Users/HelixServer/Library/LaunchAgents/scanServer1340.plist
launchctl unload /Users/HelixServer/Library/LaunchAgents/scanServer1341.plist
launchctl unload /Users/HelixServer/Library/LaunchAgents/scanServer1342.plist
