#!/bin/bash


pushd $scanProjectBase/system > /dev/null
echo -e "\n\nUPDATING INVENTORY SCANNER SERVER\n";
pwd;
echo -e "\n";
git pull
echo -e "\nFINISHED ======= Inventory Scanner Server\n\n";

popd > /dev/null


pushd $scanProjectBase/system/node_modules/helixConnector > /dev/null
echo -e "\n\nUPDATING HELIX CONNECTOR\n";
pwd;
echo -e "\n";
git pull
echo -e "\nFINISHED ======= Helix Connector\n\n";

popd > /dev/null


pushd $scanProjectBase/node_modules > /dev/null
echo -e "\n\nUPDATING QTOOLS UTILITIES\n";
pwd;
echo -e "\n";
git pull
echo -e "\nFINISHED ======= qTools Utilities\n\n";

popd > /dev/null