#!/bin/bash
echo $scanProjectBase;

echo -e "\n\n===== Starting Inventor Scanner Servers ==================== \n";

export SCANNER_PORT=1337

echo -e "\n\nStarting scanner $SCANNER_PORT\n\n" >> ${scanProjectBase}/system/management/logs/foreverServer.log;


SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"

pushd $scanProjectBase/system/ > /dev/null
nodemon -V  --config $SCRIPT_DIR/nodemon.json  \
 ${scanProjectBase}/system/scanServer/scanServer.js
popd > /dev/null
